sudo: required

language: rust
rust:
- 1.33.0

services:
  - docker

addons:
  apt:
    packages:
      - libzmq3-dev
      - build-essential

before_install:
  - docker pull lightningnetwork/bitcoind-alpine:0.16.1-r2
  - CURRENT_DIR=$(pwd) &&
    cd /tmp &&
    git clone https://github.com/romanz/electrs &&
    cd electrs &&
    git checkout e49cef1bbcaf1710613dab4578d61b99c7dbd478 &&
    cargo install --debug --path . &&
    cd $CURRENT_DIR
  - ls $HOME/.cargo/bin

install:
  - RUST_BACKTRACE=1 cargo build --no-default-features --verbose

script:
  - RUST_BACKTRACE=1 cargo test -- --test-threads=1