sudo: required

language: rust
rust:
- 1.38.0

addons:
  apt:
    packages:
      - libzmq3-dev
      - build-essential

before_install:
  - sudo apt-add-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install bitcoind -y
  - CURRENT_DIR=$(pwd) &&
    cd /tmp &&
    git clone https://github.com/romanz/electrs &&
    cd electrs &&
    git checkout a61e1b3b7a150c52188fc7c412233068c156c56b &&
    cargo install --debug --path . &&
    cd $CURRENT_DIR
  - ls $HOME/.cargo/bin

install:
  - RUST_BACKTRACE=1 cargo build --no-default-features --verbose

script:
  - RUST_BACKTRACE=1 cargo test --package rust-wallet-grpc --all-features -- --test-threads=1
  - RUST_BACKTRACE=1 cargo run --package wallet --bin environment &
  - RUST_BACKTRACE=1 cargo test --package wallet --all-features -- --test-threads=1 --nocapture
