[package]
name = "wallet"
version = "0.1.0"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-bitcoin/rust-wallet/"
repository = "https://github.com/rust-bitcoin/rust-wallet/"
documentation = "https://github.com/rust-bitcoin/rust-wallet/"
description = "Wallet library for Bitcoin"
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[lib]
name = "wallet"
path = "src/lib.rs"

[[bin]]
name = "wallet"
path = "src/bin/main.rs"

[dependencies]
bitcoin = "0.14"
secp256k1 = "0.11.0"
rust-crypto = "0.2"
log = "0.4"
simple_logger = "0.5"
rand = "0.5"
hex = "0.3"
bitcoin_rpc_client = "0.2.0"
bitcoin-bech32 = "0.8.0"

[dev-dependencies]
rustc-serialize = "0.3"